version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  dashboard:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
    volumes:
        - ./logs:/app/logs
        - ./static/audio:/app/static/audio
        - ./static/vendor:/app/static/vendor
        - ./static/css:/app/static/css
        - ./static/js:/app/static/js
        - ./static/favicon:/app/static/favicon
        - ./templates:/app/templates

volumes:
  redis_data:
