name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run ruff
      run: ruff check .
    - name: Run tests
      run: pytest -q
    - name: Run front-end tests
      run: |
        node tests/js/formatCurrency.test.js
        node tests/js/formatDuration.test.js
        node tests/js/main_dom_safety.test.js
        node tests/js/main_chart_load.test.js
        node tests/js/normalizeHashrate.test.js
        node tests/js/arrowIndicator.test.js
        node tests/js/audioCrossfadeTheme.test.js
        node tests/js/getBlockTimerClass.test.js
        node tests/js/blockProbability.test.js
        node tests/js/notificationsTimestamp.test.js
        node tests/js/workerUtils.test.js
        node tests/js/themeToggle.test.js
